trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    cd containers/$(testObject)
    git clone $(gitProject)
  displayName: 'Clone asset repo'

- task: Docker@2
  inputs:
    containerRegistry: 'dockehub'
    command: 'login'
  displayName: 'Docker login'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '$(Build.SourcesDirectory)/containers/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'
    arguments: '$(testObject)'
  displayName: 'Build'  
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: '$(Build.SourcesDirectory)/containers/docker-compose.yml'
    action: 'Run services'
    buildImages: false
    arguments: '$(testObject)'
  displayName: 'Run'    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      which docker

     
  displayName: 'Prepare for testing'
- task: Ant@1
  inputs:
      buildFile: 'build.xml'
      options: ' -DtestISHost=localhost -DtestObject=$(testObject) -DtestISPort=5555 -DtestISUsername=Administrator -DtestISPassword=manage -DprojectName=$(projectName) -DtestDir=$(testDir)'
      targets: 'test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
  displayName: 'Test'