# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    cat containers/docker-compose.yml
  displayName: 'Run a multi-line script'

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'containers/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'config'
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerComposeFile: 'containers/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'build'
    arguments: 'microservices-runtime'